export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      applications: {
        Row: {
          id: string;
          created_at: string;
          role: "mentor" | "judge";
          full_name: string;
          email: string;
          phone: string | null;
          linkedin: string | null;
          twitter: string | null;
          instagram: string | null;
          city: "medellin" | "bogota" | "both";
          availability: string | null;
          mentor_primary_skills: string | null;
          mentor_monad_experience: boolean | null;
          mentor_monad_experience_details: string | null;
          mentor_blockchain_experience: string | null;
          mentor_non_technical_skills: string | null;
          mentor_previous_experience: boolean | null;
          mentor_previous_details: string | null;
          mentor_bio: string | null;
          mentor_why: string | null;
          mentor_team_commitment: string | null;
          judge_current_role: string | null;
          judge_years_blockchain: number | null;
          judge_years_total: number | null;
          judge_bio: string | null;
          judge_technical_level: string | null;
          judge_expertise_areas: string[] | null;
          judge_specific_experience: string[] | null;
          judge_previous_experience: boolean | null;
          judge_previous_details: string | null;
          judge_criteria_ranking: Json | null;
          judge_conflicts: string | null;
          judge_other_conflicts: string | null;
          judge_why: string | null;
          status: "pending" | "approved" | "rejected";
          reviewed_at: string | null;
          reviewed_by: string | null;
          reviewer_notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          role: "mentor" | "judge";
          full_name: string;
          email: string;
          phone?: string | null;
          linkedin?: string | null;
          twitter?: string | null;
          instagram?: string | null;
          city: "medellin" | "bogota" | "both";
          availability?: string | null;
          mentor_primary_skills?: string | null;
          mentor_monad_experience?: boolean | null;
          mentor_monad_experience_details?: string | null;
          mentor_blockchain_experience?: string | null;
          mentor_non_technical_skills?: string | null;
          mentor_previous_experience?: boolean | null;
          mentor_previous_details?: string | null;
          mentor_bio?: string | null;
          mentor_why?: string | null;
          mentor_team_commitment?: string | null;
          judge_current_role?: string | null;
          judge_years_blockchain?: number | null;
          judge_years_total?: number | null;
          judge_bio?: string | null;
          judge_technical_level?: string | null;
          judge_expertise_areas?: string[] | null;
          judge_specific_experience?: string[] | null;
          judge_previous_experience?: boolean | null;
          judge_previous_details?: string | null;
          judge_criteria_ranking?: Json | null;
          judge_conflicts?: string | null;
          judge_other_conflicts?: string | null;
          judge_why?: string | null;
          status?: "pending" | "approved" | "rejected";
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          reviewer_notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          role?: "mentor" | "judge";
          full_name?: string;
          email?: string;
          phone?: string | null;
          linkedin?: string | null;
          twitter?: string | null;
          instagram?: string | null;
          city?: "medellin" | "bogota" | "both";
          availability?: string | null;
          mentor_primary_skills?: string | null;
          mentor_monad_experience?: boolean | null;
          mentor_monad_experience_details?: string | null;
          mentor_blockchain_experience?: string | null;
          mentor_non_technical_skills?: string | null;
          mentor_previous_experience?: boolean | null;
          mentor_previous_details?: string | null;
          mentor_bio?: string | null;
          mentor_why?: string | null;
          mentor_team_commitment?: string | null;
          judge_current_role?: string | null;
          judge_years_blockchain?: number | null;
          judge_years_total?: number | null;
          judge_bio?: string | null;
          judge_technical_level?: string | null;
          judge_expertise_areas?: string[] | null;
          judge_specific_experience?: string[] | null;
          judge_previous_experience?: boolean | null;
          judge_previous_details?: string | null;
          judge_criteria_ranking?: Json | null;
          judge_conflicts?: string | null;
          judge_other_conflicts?: string | null;
          judge_why?: string | null;
          status?: "pending" | "approved" | "rejected";
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          reviewer_notes?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
